tfl:
  base_url: "https://api.tfl.gov.uk"
  include_modes:
    - tube
    - dlr
    - overground
    - elizabeth-line
  stoppoint_station_types:
    - NaptanMetroStation
    - NaptanRailStation
  route_sequence:
    params:
      serviceTypes: "Regular"
  outputs:
    stoppoints_json: "tfl_stop_points_stations.json"
    lines_by_mode_json: "tfl_lines_by_mode.json"
    route_sequences_dir: "tfl_route_sequences"

thames:
  os_open_rivers_file: "oprvrs_gb.gpkg"
  os_open_rivers_layer: "watercourse_link"
  outputs:
    centerline_geojson: "thames_centerline.geojson"

boundary:
  arcgis:
    timeouts_seconds:
      where: 120
  sources:
    regions_featureserver_0: "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/Regions_December_2021_EN_BGC_2022/FeatureServer/0"
    london_region_code: "E12000007"
  outputs:
    regions_gpkg: "ons_regions_2021_en_bgc.gpkg"
    regions_layer: "regions2021"



